KishoriCloset::CONTACT_EMAIL = "kishoricloset@gmail.com"
KishoriCloset::CONTACT_PHONE = "+918722403536"
KishoriCloset::WHATSAPP_NUMBER = "918722403536"
KishoriCloset::WHATSAPP_URL = "https://wa.me/#{KishoriCloset::WHATSAPP_NUMBER}"
KishoriCloset::FACEBOOK_URL = "https://www.facebook.com/share/1J2w3NGMZu/"
KishoriCloset::INSTAGRAM_URL = "https://www.instagram.com/kishoricloset?igsh=dm5tY2dndTlsMmNo&igsi=dm5tY2dndTlsMmNo"
